USE customers;

SHOW columns
FROM  sc_customertable ;

 
-- (Updating Currency Values:
--Ensured accurate representation of currency values by rounding the "Sales_per_customer" column to two decimal places.
-- UPDATE Sales Field to two decimal places for better currency value)
UPDATE sc_customertable 
SET  Sales_per_customer = (SELECT ROUND(Sales_per_customer, 2))
;

-- (uplicate Data Check:
-- Identified and highlighted duplicate rows in the dataset based on specific criteria.)
WITH dup_rows AS 
(
SELECT *,
		ROW_NUMBER() OVER (PARTITION BY Customer_Id, Sales_per_customer, Customer_City, Department_Name, Market ORDER BY Customer_Id ) AS dup_row_num
FROM sc_customertable
)

SELECT * 
FROM dup_rows
WHERE dup_row_num = 2;

-- (Updating Late Delivery Risk Column:
-- Enhanced clarity by converting values in the "Late_delivery_risk" column from binary to "YES" or "NO".)
ALTER TABLE sc_customertable  MODIFY COLUMN Late_delivery_risk VARCHAR(10);

UPDATE sc_customertable  
SET Late_delivery_risk = (select CASE WHEN Late_delivery_risk = 1 THEN "YES" 
								  WHEN Late_delivery_risk = 0 THEN "NO" 
                                 END AS Late_delivery_risk );


-- ("consumer" segment has the highest average sales.
-- Analytical Business Question Answered: The "Consumer" customer segment generates the highest average revenue per customer, indicating potential marketing opportunities to further engage this segment.)
SELECT 
	Customer_Segment
	, ROUND(AVG(Sales_per_customer),2) AS Avg_Sale_Per_Customer_segment
FROM sc_customertable
GROUP BY Customer_Segment
ORDER BY Avg_Sale_Per_Customer_segment DESC;


-- Top 5 market (region) that generates the highest total sales?
SELECT 
	cust.Market
    ,ROUND(SUM(Sales_per_customer),2) AS Total_revenue
FROM sc_customertable cust
GROUP BY cust.Market;

--


-- Do customers in certain cities FROM THE USA tend to experience a higher late delivery risk?
SELECT 
	Customer_City
    ,(COUNT(CASE WHEN Late_delivery_risk = "YES" THEN 1 ELSE 0 END)) AS Late_delivery_risk_per_city
FROM sc_customertable
WHERE Customer_Country = "United States"
GROUP BY Customer_City
ORDER BY Late_delivery_risk_per_city DESC;





-- FIND OUT THE AMOUNT OF LATE DELIVERIES COMPARED TO ACTUAL LATE DELIVERY 
WITH Delivery_comaprison AS (
SELECT 
    Customer_City,
    COUNT(CASE WHEN Late_delivery_risk = 1 THEN 1 ELSE 0 END) AS Late_delivery_risk_count,
    SUM(CASE WHEN Delivery_Status = 'Late Delivery' THEN 1 ELSE 0 END) AS Late_delivery_count
FROM sc_customertable
WHERE Customer_Country = 'United States'
GROUP BY Customer_City
ORDER BY Late_delivery_count DESC)

SELECT 
	Customer_City
	,Late_delivery_risk_count
    ,Late_delivery_count
    ,ROUND((Late_delivery_count/Late_delivery_risk_count)*100, 2 )AS Late_delivery_percentage
    
    FROM Delivery_comaprison;



-- Order every department by the highest average sales per customer?
SELECT 
	Department_Name
	,ROUND(AVG(Sales_per_customer),2)AS Average_Department_Sale
FROM sc_customertable
GROUP BY Department_Name
ORDER BY Average_Department_Sale DESC;

-- Find the total revenue generated by each department
SELECT 
	Department_Name
	,ROUND(SUM(Sales_per_customer),2)AS Total_Revenue_Per_Department
FROM sc_customertable
GROUP BY Department_Name
ORDER BY Total_Revenue_Per_Department DESC;
    
-- The top 10 cities generating the highest revenues in the USA
SELECT 
	Customer_City
    ,ROUND(SUM(Sales_per_customer),2)AS Total_Revenue_Per_City
FROM sc_customertable
WHERE Customer_Country = "United States"
GROUP BY Customer_City
ORDER BY Total_Revenue_Per_City DESC
LIMIT 10;

-- The top 10 cities generating the highest revenues in the Puerto Rico
SELECT 
	Customer_City
    ,ROUND(SUM(Sales_per_customer),2)AS Total_Revenue_Per_City
FROM sc_customertable
WHERE Customer_Country = "Puerto Rico"
GROUP BY Customer_City
ORDER BY Total_Revenue_Per_City DESC
LIMIT 10;

-- What customer segment brings in the highest revenue
SELECT 
	Customer_Segment
    ,ROUND(SUM(Sales_per_customer),2)AS Total_Revenue_Per_Segment
FROM sc_customertable
GROUP BY Customer_Segment
ORDER BY Total_Revenue_Per_Segment DESC
LIMIT 10;

-- Find the top 5 highest revenue generating customers
SELECT 
	Customer_Id
    ,ROUND(SUM(Sales_per_customer),2)AS Total_revenue_per_customer
FROM sc_customertable
GROUP BY Customer_Id
ORDER BY Total_revenue_per_customer DESC
LIMIT 5;


-- FIND OUR TOP 10 MOST SELLING PRODUCTS IN THE USA
SELECT 
	pt.Product_Name
    ,ROUND(SUM(ot.Order_Item_Total),2) AS Product_revenue
FROM sc_producttable pt
LEFT JOIN sc_order ot
ON pt.Product_Card_Id = ot.Order_Product_Id
GROUP BY pt.Product_Name
ORDER BY Product_revenue DESC
LIMIT 10;








SELECT * FROM sc_customertable
LIMIT 10;

SELECT * FROM sc_producttable
LIMIT 10;

SELECT * FROM sc_order
LIMIT 10;
